### PR TITLE
Feature/auth

### PR DESCRIPTION
**Pull request by simpleman19**

### CODE REVIEW

**Comment by jake6642** [comment]
Pressing the logout button and/or navigating to localhost:5000/logout doesn't seem to be removing authentication. I can easily navigate to the other page, use the api test and it will tell me that admin is still logged in.

**Comment by jake6642** [comment]
It is much better now, but I still can't logout then login. It keeps me authenticated. If I enter a new username and password, it is still keeping me authenticated as the first login

**Comment by dee-dee-raye** [comment]
I added in some prints to see what it said for my session['username']. I only see None. Is that to be expected? It does seem like it is working. When I logout and try to log back in with gibberish it doesn't let me. It will let me with a different user account. So that seems good.

**Comment by simpleman19** [comment]
The user is currently only set in the g.current_user when their token or password is verified, I have the option to set the session username but I am not currently using it.  Technically setting something in the session is the wrong way to do it.  I use some session information to store credentials denied just because it was an easy way to hold the information across the authentication failure due to app context switching.

**Comment by simpleman19** [comment]
Just pushed some changes for token expiration and pulled out username session stuff.  Hopefully this corrects the logout issue, if not I may have to look at it on Jacob's machine

**Comment by epielemeier** [comment]
Works on everyone's machine except Jacob's! Yay!

**Pull request merged**
