### PR TITLE
Feature/deletion

### PR DESCRIPTION
**Pull request by simpleman19**

### CODE REVIEW

**Comment by dee-dee-raye** [comment]
I was able to delete customers great. I can't delete events though. The event is removed from the table while the modal is up, but is loaded back into the table after.

**Comment by dee-dee-raye** [comment]
I'm seeing "Could not find customer to delete. " in my terminal when I try to delete an event.

**Comment by simpleman19** [comment]
Fixed event's not deleting, copied from customer but didn't change urls

**Comment by dee-dee-raye** [comment]
Yeah, it's working now!

**Comment by dee-dee-raye** [comment]
It all looks good to me

**Comment by jake6642** [comment]
Our requirements say that users can add/update/delete **Customer** and **Events**. Admins' only real power is being able to add/update/delete Users. 

As an admin, I was able to Add/Update/Delete Events, Customers, and Users. This is good
As a User, I was able to:
**Add** - Events, Customers, _Users_ (I shouldn't be able to add a user. I can write a separate defect, or we can handle it in this story)
**Update** - Events, Customers (this is all good)
**Delete** - Customers (I should be able to delete events according to the requirements)

**Comment by simpleman19** [comment]
Fixed the event delete by normal user, really not sure how that code got in there...  Also the add issue should probably be covered under a defect for add since I was only covering deletion.  I can fix it under this if necessary though

**Comment by jake6642** [comment]
Cool. I'll merge it and write a defect for non-admins being able to add users.

It looks really good.

**Pull request merged**
