### PR TITLE
Feature/rest customer

### PR DESCRIPTION
**Pull request by epielemeier**
In #27 Jacob implemented his API calls for `GET` users, `GET` user, and `POST` user. I didn't bother with any of that; it seemed like a lot of work just to write more javascript.

However! The `DELETE` API for customer is implemented thanks to Chance's user story. I moved it to the customer API route to match the others.

### CODE REVIEW

**Review by simpleman19 — DISMISSED** [review]
Looks good to me

**Review by simpleman19 — CHANGES_REQUESTED** [review]
Getting an error about request not iterable on an add.  Line 28 in customer model inside of validate and save:  if 'name' in customer_data:

**Comment by epielemeier** [comment]
Good catch. Forgot to update a parameter for a changed function. It should be good now.

**Review by jake6642 — APPROVED** [review]
There is no validation for formatting for phone numbers, but that didn't exist before making it RESTful. It looks good and works on mine.

**Pull request merged**
