### PR TITLE
Feature/pd modify table

### PR DESCRIPTION
**Pull request by simpleman19**
Seat modification is working.

In order to test it, you will have to import a guest list to an event then run a command that I added called run_ga_all to manage.py which will run the genetic algo on all of the events in the database to update tables since it doesn't happen on import yet.

Also I already opened a defect in version one for the table numbering issue...

### CODE REVIEW

**Comment by dee-dee-raye** [comment]
I pulled it down and everything worked great for me. I was able to move guests around and reload it and have them be where I moved them. One thing though, I noticed the print button wasn't on the page. Are we waiting to add that in later?

**Comment by simpleman19** [comment]
Added a button for printing seating chart, not exactly sure when the button should have been created

**Comment by dee-dee-raye** [comment]
Looks good! Yeah, I don't know when it should have been created either. I noticed on the pdf the titles are running over, so I'm going to make a defect on version1 and work that out.

**Comment by jake6642** [comment]
After doing a branch reset and remerging this into dev, the format of the page looks much better. I still can't create a seating chart from the button. It gives me the "No Such File" error.

**Comment by simpleman19** [comment]
The print issue is a defect on Dee Dee's printing story

**Pull request merged**
