### PR TITLE
Fix unit tests reference

### PR DESCRIPTION
**Pull request by epielemeier**
Running `manage.py test` would break because `pytest` isn't included in `requirements.txt`:
https://github.com/simpleman19/eagleEvents/blob/506e2c4d59cc3057357cebbda0ae1be33506c884/manage.py#L39-L44

I added some example tests to help with the learning curve:
https://github.com/simpleman19/eagleEvents/blob/07d874960c77540f05e64868f90c5f19d5076ffe/test/test_company.py#L5-L18

@simpleman19 Should there be anything in `test/__init__.py`? Or should I delete this file since it's empty?

If anyone wants this immediately, go ahead and review it otherwise let's leave it up to Chance to review.

### CODE REVIEW

**Comment by simpleman19** [comment]
Looks fine to me, the __init__.py is how python knows what folders are packages and an be imported from so you have to leave it

You will need to add the pacakges to the requirements.txt file though.  To do that just run: pip freeze > requirements.txt

**Comment by simpleman19** [comment]
The test was in there because I copied the manage file from a different project and just left that in just in case anyone wanted to write unit tests

**Comment by epielemeier** [comment]
@simpleman19 by adding packages do you mean these? https://github.com/simpleman19/eagleEvents/pull/2/commits/666f1b62c73c03173bfff3884f580f747046cb88

**Comment by jake6642** [comment]
@epielemeier The __init__.py is required in each directory that will be considered a package. These packages are not the same as the things in Requirements.txt, but rather, they provide a means for us to import other "classes." WIthout the __init__.py in the models directory, you would not be able to import Guest, Event, etc. from the models directory. The same goes for all routes directory. 

https://stackoverflow.com/questions/448271/what-is-init-py-for

**Pull request merged**
