### PR TITLE
Feature/design

### PR DESCRIPTION
**Pull request by ghost**
Fixed the Navbar Issue

### CODE REVIEW

**Review by simpleman19 — CHANGES_REQUESTED** [review]
I'm still getting an issue with the navbar not having the correct active mark.  It looks like it swaps for about half a second then goes back to the events as active

Also looks like there was a commit with a merge in progress in the Events.py routes file.

**Comment by ghost** [comment]
Fixed it.

**Review by epielemeier — CHANGES_REQUESTED** [review]
This doesn't handle nested navigation.

i.e.
1. Go to Customers list page
   * "Customers" on nav bar is highlighted
2. Click on customer to go to add/update customer page
   * "Events" on navbar is highlighted
   * (Expected "Customers" to still be highlighted)

**Comment by ghost** [comment]
Made fixes for nested navigation.

**Review by jake6642 — APPROVED** [review]

**Pull request merged**
